# To boot the app run the following:
# docker compose run auto-gpt
# NOTE: Version 3.9 requires at least Docker Compose version 2 and Docker Engine version 20.10.13!

version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt
    env_file:
      - .env
    ports:
      - "8000:8000" # remove this if you just want to run a single agent in TTY mode
    profiles: ["exclude-from-up"]
    volumes:
      - ./data:/app/data
      ## allow auto-gpt to write logs to disk
      - ./logs:/app/logs
      ## uncomment following lines if you want to make use of these files
      ## you must have them existing in the same folder as this docker-compose.yml
      #- type: bind
      #  source: ./ai_settings.yaml
      #  target: /app/ai_settings.yaml
      #- type: bind
      #  source: ./prompt_settings.yaml
      #  target: /app/prompt_settings.yaml
